import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const farsiFont = localFont({
  src: "./fonts/Shabnam.woff", // Ensure this path is correct
  variable: "--font-farsi-shabnam",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="fa" dir="rtl"> {/* Setting Farsi as the default language and RTL direction */}
      <body
          className={`${farsiFont.variable}`}
          style={{fontFamily: 'var(--font-farsi-shabnam)'}} // Set Shabnam font as default
      >
      {children}
      </body>
      </html>
  );
}
